Bulding an emotion detection model using KNN. Emotion detection model using KNN is actually inefficient since KNN checks your input with every dataset it has stored, this is done for the sake trying things out

Pipeline : Sentence -> Vectorization -> KNN -> Emotion prediction

First we have analyse the dataset we are working with

In [1]:
import pandas as pd
df=pd.read_csv("emotion_dataset.csv")
df.head()

                          text  emotion
0                I am thrilled  excited
1  Just another regular moment  neutral
2    Nothing special happening  neutral
3        I hate this situation    angry
4          This is so exciting  excited

In [3]:
df.shape

(300, 2)

We have 300 rows with 2 columns

Let's vectorize the text input data

In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [8]:
vectorizer = TfidfVectorizer()
X=vectorizer.fit_transform(df["text"])
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1132 stored elements and shape (300, 59)>

In [10]:
vectorizer.get_feature_names_out()

array(['about', 'am', 'amazing', 'and', 'angry', 'another', 'beautiful',
       'best', 'can', 'day', 'depressed', 'down', 'ever', 'excited',
       'exciting', 'feel', 'feeling', 'feels', 'for', 'forward',
       'frustrating', 'furious', 'going', 'great', 'happening', 'happy',
       'hate', 'have', 'is', 'it', 'just', 'life', 'lonely', 'looking',
       'mad', 'makes', 'me', 'meeting', 'moment', 'normal', 'nothing',
       'now', 'really', 'regular', 'right', 'sad', 'situation', 'so',
       'special', 'store', 'super', 'terrible', 'the', 'this', 'thrilled',
       'to', 'today', 'very', 'wait'], dtype=object)

In [12]:
y=df["emotion"]
y

0      excited
1      neutral
2      neutral
3        angry
4      excited
        ...
295    neutral
296        sad
297      angry
298      angry
299      happy
Name: emotion, Length: 300, dtype: object

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [16]:
model=KNeighborsClassifier(n_neighbors=5,metric="cosine")
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [17]:
model.fit(X_train,y_train)

KNeighborsClassifier(metric='cosine')

In [19]:
acc=accuracy_score(y_test,model.predict(X_test))
print("Accuracy score : "+str(acc*100)+"%")

Accuracy score : 100.0%

Overfitting model

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

sentence="I am furious"
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["text"])
sentence_vectorized = vectorizer.transform([sentence])
print(model.predict(sentence_vectorized))

['angry']

In [30]:
while True:
    n=input("Enter a sentence :")
    if n=="bye":
        print("Bye")
        break
    n=vectorizer.transform([n])
    print("I think you are : "+model.predict(n))

Enter a sentence :hi
['I think you are : sad']
Enter a sentence :why
['I think you are : sad']
Enter a sentence :i love you
['I think you are : sad']
Enter a sentence :i am so angry
['I think you are : angry']
Enter a sentence :i am furious
['I think you are : angry']
Enter a sentence :I am thrilled
['I think you are : excited']
Enter a sentence :bye
Bye